version: '3.8'
services:
    multiplayer:
      build: .
      ports:
        - '5002:5002'
        - '4000:4000'
      image: multiplayer
      container_name: multiplayer
      networks:
        - hs-services
      environment:
        - JWT_PASSWORD=Z6LXQoOMSVkAyf0TLkOMSn9jigB8VD7m

networks:
    hs-services:
        driver: bridge
        name: hs-services